# Manual endpoint smoke tests

GET http://127.0.0.1:8000/health
Accept: application/json

###

POST http://127.0.0.1:8000/auth/token
Content-Type: application/x-www-form-urlencoded

username=manager&password=manager123

###

GET http://127.0.0.1:8000/manager/orders/
Accept: application/json

###
